FROM node:16

# Set the working directory
WORKDIR /frontend

# Copy only package.json and package-lock.json for installing dependencies
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY frontend/ . 

# Build and expose the application
RUN npm run build --verbose
EXPOSE 5000
CMD ["npm", "start"]
