services:
  # Nginx 서비스 추가
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/eugene/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/eugene/certbot/www:/var/www/certbot
      - /home/eugene/certbot/conf:/etc/letsencrypt
    depends_on:
      - backend-container
      - frontend-container
      - ai-container
    networks:
      - baseball-server_default

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/eugene/certbot/www:/var/www/certbot
      - /home/eugene/certbot/conf:/etc/letsencrypt
    networks:
      - baseball-server_default

  # 기존 Backend
  backend-container:
    image: baseball-server-backend:latest
    container_name: backend-container
    ports:
      - "3001:3000"
    restart: always
    networks:
      - baseball-server_default

  # 기존 Frontend
  frontend-container:
    image: baseball-server-frontend:latest
    container_name: frontend-container
    ports:
      - "5000:5000"
    restart: always
    networks:
      - baseball-server_default

  # 기존 AI 서비스
  ai-container:
    image: baseball-server-ai:latest
    container_name: ai-container
    ports:
      - "8000:8000"
    volumes:
      - /home/eugene/app/baseball-server/ai-service/logs:/ai-service/logs
      - /home/eugene/app/baseball-server/ai-service/data:/ai-service/data
    restart: always
    networks:
      - baseball-server_default
  selenium-hub:
    image: selenium/standalone-chrome:4.10.0
    container_name: selenium-hub
    ports:
      - "4444:4444"  # Selenium Hub 포트
    networks:
      - baseball-server_default

  # Selenium Node
  selenium-node-chrome:
    image: selenium/node-chrome:4.10.0
    container_name: selenium-node-chrome
    depends_on:
      - selenium-hub
    networks:
      - baseball-server_default

networks:
  baseball-server_default:
    driver: bridge