services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile # 상대 경로
    container_name: backend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - shared-data:/app/shared # 공유 볼륨 마운트
    depends_on:
      - frontend # backend는 frontend 빌드가 완료되어야 실행됨

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile # 상대 경로
    container_name: frontend
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - shared-data:/app/shared # 공유 볼륨 마운트
    command: >
      sh -c "npm install && npm run build && cp -r /app/frontend/build /app/shared" # build 파일을 공유 볼륨으로 복사

volumes:
  shared-data: # 공유 볼륨 정의
