FROM python:3.9-slim

WORKDIR /app

# 로그 디렉토리 생성
RUN mkdir -p /app/logs

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
