FROM node:16

# Set the working directory
WORKDIR /backend

# Copy only package.json and package-lock.json for installing dependencies
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend application
COPY backend/ . 

# Build and expose the application
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
