# Use a Node.js base image
FROM node:16

# Set the working directory
WORKDIR /home/app/backend

# Copy package.json and install dependencies
COPY backend/package*.json ./
RUN npm install

# Copy the rest of the application
COPY backend/ .

# Build the application
RUN npm run build

# Expose the port the app will run on
EXPOSE 3000

# Command to run the application
CMD ["pm2", "start", "dist/main.js"]
