export enum Team {
  LG_TWINS = 'LG_TWINS',
  SAMSUNG_LIONS = 'SAMSUNG_LIONS',
  KIWOOM_HEROS = 'KIWOOM_HEROS',
  HANHWA_EAGLES = 'HANHWA_EAGLES',
  KT_WIZ = 'KT_WIZ',
  DOOSAN_BEARS = 'DOOSAN_BEARS',
  NC_DINOS = 'NC_DINOS',
  SSG_LANDERS = 'SSG_LANDERS',
  KIA_TIGERS = 'KIA_TIGERS',
}
