name: Docker Based CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to AWS EC2 with Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      # Backend Docker 이미지 빌드
      - name: Build Backend Docker image
        run: |
          cd backend
          docker build -t backend-image -f Dockerfile.backend .

      # Backend Docker 이미지 태그 및 푸시
      - name: Tag and Push Backend Docker image to ECR
        run: |
          docker tag backend-image:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/baseball-project-backend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/baseball-project-backend:latest

      # Frontend Docker 이미지 빌드
      - name: Build Frontend Docker image
        run: |
          cd frontend
          docker build -t frontend-image -f Dockerfile.frontend .

      # Frontend Docker 이미지 태그 및 푸시
      - name: Tag and Push Frontend Docker image to ECR
        run: |
          docker tag frontend-image:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/baseball-project-frontend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/baseball-project-frontend:latest

      - name: Execute remote SSH commands on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            # EC2에 SSH로 접속하여 Docker Compose로 컨테이너 실행

            # 1. 기존 Docker 컨테이너 중지 및 삭제 (있으면 삭제)
            docker-compose -f /home/ec2-user/app/baseball-server/docker-compose.yml down || true

            # 2. ECR에서 Backend 및 Frontend Docker 이미지 풀(pull)
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/baseball-project-backend:latest
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/baseball-project-frontend:latest

            # 3. .env 파일 생성
            echo "${{ secrets.ENV }}" > /home/ec2-user/app/baseball-server/backend/.env

            # 4. Docker Compose로 서비스를 빌드하고 시작
            cd /home/ec2-user/app/baseball-server
            docker-compose -f docker-compose.yml up -d --build
