name: main branch auto ci process script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ec2-user/app/baseball-server

            # 디렉토리 생성
            mkdir -p /home/ec2-user/app/baseball-server/backend/config

            # Save the YAML configuration file
            echo "${{ secrets.ENV }}" > /home/ec2-user/app/baseball-server/backend/.env

            # Pull latest changes from the repository
            git config --global url.https://${{ secrets.GIT_TOKEN }}@github.com/.insteadOf https://github.com/

            git reset --hard
            git pull origin main

            cd frontend
            npm install
            npm run build
            cd ..

            if [ -d "frontend/build" ]; then
              # Create a directory to hold the public files if it doesn't exist
              mkdir -p backend/public
              
              # Remove existing files in the public directory to avoid conflicts
              rm -rf backend/public/*

              # Copy build files from React to the public directory
              cp -r frontend/build/* backend/public/
            else
              echo "frontend/build directory does not exist"
              exit 1
            fi

            # Stop all pm2 processes and ignore errors if there are none
            pm2 stop all || true

            # Build the application
            cd backend
            npm run build

            # Start the application
            pm2 start dist/main.js
