name: main branch auto ci process script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build React frontend
        run: |
          cd frontend  # React 앱이 있는 디렉토리로 이동
          npm install
          npm run build

      - name: Copy React build files to public
        run: |
          # Create a directory to hold the public files if it doesn't exist
          mkdir -p public

          # Remove existing files in the public directory to avoid conflicts
          rm -rf public/*

          # Copy build files from React to the public directory
          cp -r frontend/build/* public/

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ec2-user/app/baseball-server

            # 디렉토리 생성
            mkdir -p /home/ec2-user/app/baseball-server/config

            # Save the YAML configuration file
            echo "${{ secrets.APPLICATION_YML }}" > /home/ec2-user/app/baseball-server/config/application.yml

            # Pull latest changes from the repository
            git reset --hard
            git pull origin main

            # Stop all pm2 processes and ignore errors if there are none
            pm2 stop all || true

            # Install dependencies
            npm install --legacy-peer-deps

            # Build the application
            npm run build

            # Start the application
            pm2 start dist/main.js
