name: main branch auto ci process script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }} # EC2 인스턴스의 IP 주소
          username: ${{ secrets.REMOTE_USER }} # EC2 인스턴스의 사용자 이름 (예: ubuntu, ec2-user)
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # PEM 형식의 개인 SSH 키
          port: ${{ secrets.REMOTE_SSH_PORT }} # SSH 포트 (기본 포트는 22)
          script: |
            cd /home/ec2-user/app/Nest-Project
            git pull origin main
            pm2 stop all || true  # 모든 프로세스를 중지하고, 중지하지 않은 경우 무시
            npm install --legacy-peer-deps
            npm run build
            pm2 start dist/main.js
